# This is a generated file. Not intended for manual editing.
services:
  airypay.discord:
    build:
      context: "C:\\Users\\oqrom\\RiderProjects\\airy-pay"
      dockerfile: "src/AiryPay.Discord/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AiryPay.Discord.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "airypay.discord:dev"
    ports: []
    volumes:
    - "C:\\Users\\oqrom\\RiderProjects\\airy-pay\\src\\AiryPay.Discord:/app:rw"
    - "C:\\Users\\oqrom\\RiderProjects\\airy-pay:/src:rw"
    - "C:\\Users\\oqrom\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  airypay.web:
    build:
      context: "C:\\Users\\oqrom\\RiderProjects\\airy-pay"
      dockerfile: "src/AiryPay.Web/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AiryPay.Web.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "airypay.web:dev"
    ports: []
    volumes:
    - "C:\\Users\\oqrom\\RiderProjects\\airy-pay\\src\\AiryPay.Web:/app:rw"
    - "C:\\Users\\oqrom\\RiderProjects\\airy-pay:/src:rw"
    - "C:\\Users\\oqrom\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
